hybrid.sh

I don't know if you want me to create an screenshot of the theme or you want to do it yourself, If you need something else to merge it, please let me know!

Hybrid theme

---

_apply-colors.sh
aci.sh
aco.sh
azu.sh
base.sh
bim.sh
cai.sh
chalk.sh
content/howto.md
dracula.sh
elementary.sh
elic.sh
elio.sh
flat.sh
freya.sh
hybrid.sh
jup.sh
mar.sh
miu.sh
monokai.dark.sh
nep.sh
pali.sh
sat.sh
shel.sh
solarized.dark.sh
solarized.light.sh
tin.sh
ura.sh
vag.sh

Hey,
I've added support for elementary OS 0.3 freya. 
Beside that I tried to unify the scripts and outsourced all the redundant parts into a separate script.

Freya support

---

hemisu.dark.sh
hemisu.light.sh

This is a port of Terminal.app [Hemisu color themes](https://noahfrederick.com/log/hemisu-for-os-x-terminal/) by Noah Frederick.

Hemisu themes

---

peppermint.sh

This is a port of Terminal.app [Peppermint color theme](https://noahfrederick.com/log/lion-terminal-theme-peppermint/) by Noah Frederick.

Peppermint theme

---

ocean.dark.sh

[Ocean theme](https://github.com/fabianperez/ocean-dark-iterm) by [Fabian Perez](https://github.com/fabianperez)
"An iTerm.app theme based on the base16 Ocean theme. "
It is licensed MIT.

Ocean theme

---

smyck.sh

[SMYCK color theme](http://color.smyck.org/) originally created by John-Paul Bader ([hukl](https://github.com/hukl)), licensed under the MIT License.

SMYCK theme by John-Paul Bader

---

material.sh

This is a port of Material color theme by [Mitchel van Eijgen](https://gist.github.com/mvaneijgen/4c56701215847dd5ddcf) and [Liu Xinan](https://gist.github.com/xinan/ca2b82fef6aaa0d1e099).

Material theme

---

tomorrow.night.blue.sh
tomorrow.night.bright.sh
tomorrow.night.eighties.sh
tomorrow.night.sh
tomorrow.sh

This is a port of [Tomorrow color theme set](https://github.com/chriskempson/tomorrow-theme) by [Chris Kempson](https://github.com/chriskempson).
Released under the MIT License.

Tomorrow themes

---

content/themes.md

Before the url was the same theme chalk

minor fix to get correct flat theme url

---

themes/one.dark.sh
themes/one.light.sh

This is a port of [One Dark & Light theme set](https://github.com/nathanbuchar/one-dark-terminal) by [Nathan Buchar](https://github.com/nathanbuchar). 
"A Terminal theme that mimics the One Dark theme made by the Atom team."
License: MIT

One Dark & One Light

---

_apply-colors.sh

Fix typo in condition

---

_apply-colors.sh
themes/solarized.dark.sh
themes/solarized.light.sh

Based on https://github.com/Anthony25/gnome-terminal-colors-solarized

Fix Solarized colors

---

_apply-colors.sh

This allows sourcing via [zgen](https://github.com/tarjoilija/zgen) for automation.

Only display palette when run interactively

---

content/install.md
script/gogh-with-profile.sh
script/gogh.sh

Instead of creating profiles with the name of the current profile, it uses the theme name to set the profile name.
The PR uses the issue #38 as reference.

[DONE] Create profile with CLI Script

---

README.md
content/install.md

As discussed in another issue and PR, turning the profile creation optional would facilitate for those who are new to Gogh (or even to the concept of terminals).

[DONE] Profile with CLI Script is optional

---

themes/gruvbox.dark.sh

Hi @Mayccoll, I created a **gruvbox dark** theme based on the original  [gruvbox-theme](https://github.com/morhetz/gruvbox) for my use. Maybe it will be useful for other users.
Cheers,

gruvbox dark theme added

---

script/gogh-with-profile.sh
script/gogh.sh

I noticed the Gruvbox Dark theme was missing from the install scripts, so I added it.

Add install option for Gruvbox Dark theme

---

themes/solarized.dark.sh

The Solarized Dark theme was very gray  and in order to make him more comfortable to work with I've changed do tonality of some colors in the color pallet.

Adding some slightly contrasting colors to the Solarized Dark theme

---

script/gogh-with-profile.sh

Hey! I think it would be great if you could download as many profiles as you want in one time.

I added an array so that you can download several profiles in one time..

---

themes/ir.black.sh

Do you want me to also add the boilerplate code which takes the profile name into consideration, i.e. scripts folder, or will you do it yourself? Let me know if you need something else to merge it.

Ported OSX 'IR_Black' theme created by Todd Werth

---

gogh.sh

gogh: some more improvements

---

apply-colors.sh

I want to resolve #29 . Let me know if something is amiss or needs more work for this pull request to be accepted.

Added support for Guake terminal

---

README.md

Ugh, forgot to add it with a main commit.

Add Srcery theme source to README.md

---

README.md
gogh.sh
themes/snazzy.sh

Add [Snazzy](https://github.com/sindresorhus/hyper-snazzy) them by Sindre Sorhus.
**Note:** This may be an updated version of current **chalk** theme, as the screenshot from which the chalk theme was derived from was also made by Sindre.

Add Snazzy theme by Sindre Sorhus

---

themes/clone-of-ubuntu.sh

For people used to use Ubuntu but forced to work on CentOS or other systems.

add a theme borrowed from Ubuntu 16.04, tested on CentOS 7

---

apply-colors.sh

I sometimes happen to work on a Windows machine with Cygwin, but I still wanted it to look like my usual terminal, including colours, so I've given it a try and made the apply-colors.sh script capable of updating colours used by Cygwin's mintty too - here's what I ended up with.

Added support for updating Cygwin's mintty colours configuration

---

gogh.sh

I'm not a guru of bash, may be there is better way of fixing this problem. But with this fix it works as it should (installing multiple themes)

fixes #121

---

index.html

So here is the update for `gh-pages` branch to make the new images visible on the website.

Update gh-pages with latest changes

---

gogh.sh
test/print-themes.sh
themes/google-dark.sh

This adds Google Dark theme by Seth Wright (http://sethawright.com)

Google Dark theme

---

themes/maia.sh

Based on Manjaro's Maia color scheme

Add Maia theme

---

themes/neon-night.sh

I adapted @chaseadamsio amazing [Visual Studio Code theme](https://marketplace.visualstudio.com/items?itemName=chaseadamsio.vscode-theme-neon-night) the best I could, this is how it looks in the Pantheon terminal:

Add neon-night

---

gogh.sh
themes/papercolor-dark.sh
themes/papercolor-light.sh

based on https://github.com/NLKNguyen/papercolor-theme
light:
dark:

Add PaperColor theme

---

gogh.sh
themes/vs-code-dark-plus.sh

Based on the Visual Studio Code dark terminal theme.

Add VS Code Dark+ theme

---

README.md

Fix some typo in README.md

---

themes/gotham.sh

Hi!  😀
I add a colorscheme named by `gotham`.
Please review this pull request!!
> https://github.com/whatyouhide/gotham-contrib
> https://github.com/whatyouhide/gotham-contrib/blob/master/shell/gotham.sh

add gotham theme

---

README.md

Hi.
I added the creator of gotham to credit.
Please confirm this Pull Request.

Add new credits

---

apply-colors.sh

Fix a typo

---

content/howto.md

Just fixed a typo on howto file

Fix typo howto

---

themes/synthwave.sh

Add SynthWave theme based on the [vscode theme by robb0wen](https://github.com/robb0wen/synthwave-vscode)

Add SynthWave theme

---

gogh.sh
themes/fairyfloss.sh
themes/fairyflossdark.sh

The Fairy Floss theme was created by @sailorhg
https://github.com/sailorhg/fairyfloss
The Fairy Floss Dark theme is a variation of the same
Signed-off-by: nisha <nishakumarx@gmail.com>

Add fairy floss themes

---

gogh.sh
test/print-themes.sh
themes/wzoreck.sh

Hi, I liked the idea of ​​this project, so I decided to create this theme with my username "wzoreck" for him :)

New Theme (Wzoreck)

---

gogh.sh
test/print-themes.sh
themes/bluloco-light.sh

Add the Bluloco Light theme created by Umut Topuzoğlu (https://github.com/uloco/theme-bluloco-light).
Should I add this link on the Credits section on README?

add theme (Bluloco Light)

---

gogh.sh
test/print-themes.sh
themes/sweet.sh

Based on the terminal theme of vscode sweet theme I "created" a terminal theme that can be used in any terminal by using your base.sh script

Adding new Terminal Theme based on sweet vscode Terminal Theme

---

gogh.sh
themes/laserwave.sh

Hi.
I added a new theme named [laserwave](https://marketplace.visualstudio.com/items?itemName=jaredkent.laserwave).
Please review and merge to your awesome project Gogh.

Add laserwave theme

---

gogh.sh
themes/sweet-eliverlara.sh

Ported over a theme called "Sweet KDE" made by EliverLara. Let me know if there is anything I should change!

Add Sweet-EliverLara theme

---

gogh.sh
themes/vs-code-light-plus.sh

Hi
Added Vs code light+ theme.
Thanks you.

Add Vs code light+ theme

---

themes/ayu-dark.sh
themes/ayu-light.sh
themes/ayu-mirage.sh

Based on [Ayu Theme](https://github.com/ayu-theme).
Closes #294.

Add Ayu themes

---

themes/dissonance.sh

Dissonance is my version of Symphonic, with red cursor and full black background

Add Dissonance theme

---

apply-colors.sh

Hi,
I've just added support for the foot terminal (https://codeberg.org/dnkl/foot). Would be great if this could be merged.
Thanks!
pfuender

support for foot terminal (https://codeberg.org/dnkl/foot)

---

gogh.sh
themes/ibm3270-hicontrast.sh

Hello! It's been a while.
Turns out I really use Gogh a lot to deal with Elementary's lack of theming support, so I thought I'd contribute this theme: it's nothing special, basically a port of X3270's default palette, but it's extremely simple and readable.

Request to merge new theme IBM 3270 (High Contrast)

---

themes/gogh.sh

I've been exploring the themes in Gogh recently, just to see which ones I like, and it turns out that Gogh and palenight are currently identical except for the name:
I like the theme, and I like the idea of having a theme named Gogh, given that that's the name of the project. So this got me thinking - why not tweak Gogh a bit to give it it's own character?
Here are some before and after shots! (Before is on the left, After is on the right)
This is just a consideration, and if you'd like I could submit it as it's own theme (not named gogh). Let me know what you think!

Tune Gogh theme to give it it's own feel

---

themes/tender.sh

This theme is based on: [https://github.com/jacoborus/tender.vim](https://github.com/jacoborus/tender.vim)

Added Tender theme

---

themes/nightfox.sh

This theme is based on https://github.com/EdenEast/nightfox.nvim

Feat: add nightfox theme

---

themes/synthwave-alpha.sh

Based on [Synthwave Alpha](https://github.com/vikpe/synthwave-alpha) color palette.

Add Synthwave Alpha theme

---

apply-colors.sh

Fix TERM checking for kitty under Darwin

---

themes/kanagawa.sh

additional theme: kanagawa them ported from https://github.com/rebelot/kanagawa.nvim

ported from rebelot/kanagawa.nvim

---

README.md
gogh.sh
themes/everforest-dark.sh
themes/everforest-light.sh

Hi! Thanks to this great tool! 
Added these new themes:
* Everforest Dark
* Everforest Light
This theme is based on: https://github.com/sainnhe/everforest
Screenshots:

Add Everforest Dark and Light theme set

---

themes/google-light.sh

I'm pretty sure these are the wrong way around.

swap the labels between the cyan and purple colours

---

themes/breath-darker.sh

Greetings.
Testing some themes,  I liked breath and thanks to deniandriancode for that, but I am more into darker themes so I tweak it a little and added highlight that looks good, here some ss to look for:
Also, thanks for this project. :D

Breath darker

---

themes/predawn.sh

Added Predawn Theme

---

README.md

seems to not have been updated when it was changed

Fix readme manual install directory of install scripts

---

themes/Apprentice.yml

From https://romainl.github.io/Apprentice/

Added Apprentice theme

---

apply-alacritty.py
requirements.txt

The future releases starting from **[0.13.0](https://github.com/alacritty/alacritty/commit/bd4906722a1a026b01f06c94c33b13ff63a7e044)** of the Alacritty terminal are shifting to TOML-based config, this PR adds support for the same. --Thanks

Fix(support for toml config) for newer version of Alacritty.

---

themes/Campbell.yml

References:
- https://learn.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes#creating-your-own-color-scheme
- https://gist.github.com/willwm/7a4532ba4cee2309fa2e89455f72b029#file-campbell-json

Add Campbell theme

---

themes/Selenized Dark.yml
themes/Selenized Light.yml

This PR implements the [Selenized theme](https://github.com/jan-warchol/selenized/).

Selenized Theme

---

themes/Nightfly.yml

This PR implements [Nightfly Theme](https://github.com/bluz71/vim-nightfly-colors)
Color Code Ref:
https://github.com/bluz71/vim-nightfly-colors#extra-themes

Nightfly Theme

---

themes/Moonfly.yml

This PR implements [Moonfly Theme](https://github.com/bluz71/vim-moonfly-colors)
Color Code Ref:
https://github.com/bluz71/vim-moonfly-colors#extra-themes

Moonfly Theme

---

apply-colors.sh

In the same vein as my last PR, this automatically applies a chosen theme if your terminal is `linux_vt`.

feat(linux_vt): automatically apply theme

---

themes.json

fuck, that symlink was a bad idea! That caused the deploy to fail, actually :(
https://briorg.github.io/Gogh/ this is this PR so you know it works!

fix(site): Delete new themes.json symlink

---

themes/Tomorrow Night.yml

color_09: '#808080' - Bright Black is too dark for terminal, so i modified color_09 with `#808080`

Tomorrow Night Modified

---

themes/Butrin.yml

Here's a preview of the theme for convenience

Added my theme Butrin

---

README.md
apply-colors.sh
apply-terminator.py

Asks the user to enter a name for the profile to update or create, the default is to change the "default" profile.
Then asks if wants to copy the "default" profile config settings.
Before any changes I create a terminator config backup.
Aaand that's it! To see the changes you have to close and open the terminator.
It shouldn't ask for any python dependencies cause they come w terminator install.

Terminator Support

---

themes/Quiet.yml

Tried to design a theme which would have distinguishable colors but be easy on my eyes. Happy with the result so decided to share :)

Add Quiet theme

---

themes/Sparky.yml

Hey there,
I designed/developed this pretty simple theme called Sparky; its based on Enter Shikari's *The Spark* and *Nothing is True & Everything is Possible*.
Its a little similar to Solarized but I guess it has its own spin of post-hardcore British rock.

feat: add Sparky

---

themes/Seoul256 Light.yml
themes/Seoul256.yml

This implements [Seoul256](https://github.com/junegunn/seoul256.vim)
Colour scheme based on their [urxvt files](https://github.com/junegunn/seoul256.vim/tree/master/urxvt)

Seoul256 theme

---

themes/Solarized Light.yml

updated in relation to : https://github.com/Gogh-Co/Gogh/pull/430

Update Solarized Light.yml

---

themes/Everforest Dark Hard.yml
themes/Everforest Dark Medium.yml
themes/Everforest Dark Soft.yml
themes/Everforest Light Hard.yml
themes/Everforest Light Medium.yml
themes/Everforest Light Soft.yml

I like and use Everforest Soft Themes in Vim and also made them for my terminal. I am glad to share my versions according official [Everforest Color Palette and Highlighting Semantics](https://github.com/sainnhe/everforest/blob/master/palette.md).

add Everforest flavours

---

themes/Blue Dolphin.yml

Here is a [nice theme](https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/screenshots/BlueDolphin.png) for those who is tired from solarized ))

add Blue Dolphin theme

---

themes/Modus Operandi Tinted.yml
themes/Modus Operandi.yml
themes/Modus Vivendi Tinted.yml
themes/Modus Vivendi.yml

This implements [Modus Themes](https://protesilaos.com/emacs/modus-themes)
Variants included:
- Modus Operandi
- Modus Operandi Tinted
- Modus Vivendi
- Modus Vivendi Tinted

Modus Themes

---

themes/Iceberg.yml

I added the Iceberg theme from https://github.com/cocopon/iceberg.vim

Added the Iceberg Theme

---

themes/City Lights.yml

Create a city lights color scheme based on the theme by yummygum

create city lights theme

---

themes/Astrodark.yml

Add the astrodark theme from Astronvim
https://github.com/AstroNvim/astrotheme

feat: Add astrodark theme

---

themes/Atelier Cave.yml
themes/Atelier Dune.yml
themes/Atelier Estuary.yml
themes/Atelier Forest.yml
themes/Atelier Heath.yml
themes/Atelier Lakeside.yml
themes/Atelier Plateau.yml
themes/Atelier Savanna.yml
themes/Atelier Seaside.yml
themes/Atelier Sulphurpool.yml

Atelier Schemes: read more about them at [atelierbram.github.io/syntax-highlighting/atelier-schemes/](https://atelierbram.github.io/syntax-highlighting/atelier-schemes/)

added Atelier Schemes

---

themes/Base4Tone Classic A.yml
themes/Base4Tone Classic B.yml
themes/Base4Tone Classic C.yml
themes/Base4Tone Classic D.yml
themes/Base4Tone Classic E.yml
themes/Base4Tone Classic F.yml
themes/Base4Tone Classic I.yml
themes/Base4Tone Classic L.yml
themes/Base4Tone Classic O.yml
themes/Base4Tone Classic P.yml
themes/Base4Tone Classic Q.yml
themes/Base4Tone Classic R.yml
themes/Base4Tone Classic S.yml
themes/Base4Tone Classic T.yml
themes/Base4Tone Classic U.yml
themes/Base4Tone Classic W.yml
themes/Base4Tone Modern C.yml
themes/Base4Tone Modern N.yml
themes/Base4Tone Modern W.yml

Base4Tone colorschemes with limited color palette. Read more about them at [https://atelierbram.github.io/syntax-highlighting/base4tone/](https://atelierbram.github.io/syntax-highlighting/base4tone/)

added Base4Tone colorschemes

---

themes/Base2Tone Cave.yml
themes/Base2Tone Desert.yml
themes/Base2Tone Drawbridge.yml
themes/Base2Tone Earth.yml
themes/Base2Tone Evening.yml
themes/Base2Tone Field.yml
themes/Base2Tone Forest.yml
themes/Base2Tone Garden.yml
themes/Base2Tone Heath.yml
themes/Base2Tone Lake.yml
themes/Base2Tone Lavender.yml
themes/Base2Tone Mall.yml
themes/Base2Tone Meadow.yml
themes/Base2Tone Morning.yml
themes/Base2Tone Motel.yml
themes/Base2Tone Pool.yml
themes/Base2Tone Porch.yml
themes/Base2Tone Sea.yml
themes/Base2Tone Space.yml
themes/Base2Tone Suburb.yml

Base2Tone (duotone) colorschemes. Read more about them at [base2t.one](https://base2t.one)

added Base2Tone colorschemes

---

themes/Kanagawa Lotus.yml
themes/Kanagawa Wave.yml

Kanagawa Lotus is the light variant of the Kanagawa theme set. Also renamed Kanagawa to Kanagawa Wave to make it more clear which variant is which.

Add Kanagawa Lotus

---

themes/Doom One.yml

Ported from [doom-one-theme.el in doomemacs/themes](https://github.com/doomemacs/themes/blob/v2.3.0/themes/doom-one-theme.el) originally by [hlissner](https://github.com/hlissner)

Create themes/Doom One.yml

---

apply-colors.sh
gogh.sh

Add support for Termux.
Intended to partially close #476

feat: add termux

---

themes/Nanosecond.yml

Fixed transcription error for cyan.

Fix Nanosecond

---

themes/Tempus Autumn.yml
themes/Tempus Classic.yml
themes/Tempus Dawn.yml
themes/Tempus Day.yml
themes/Tempus Dusk.yml
themes/Tempus Fugit.yml
themes/Tempus Future.yml
themes/Tempus Night.yml
themes/Tempus Past.yml
themes/Tempus Rift.yml
themes/Tempus Spring.yml
themes/Tempus Summer.yml
themes/Tempus Tempest.yml
themes/Tempus Totus.yml
themes/Tempus Warp.yml
themes/Tempus Winter.yml

I'm not the original author of the theme, and he deserves all the credit for the themes.
The original repository: https://gitlab.com/protesilaos/tempus-themes

Add Tempus themes

---

themes/Gruvbox Material Dark.yml
themes/Gruvbox Material Light.yml

Hey, I added the light version of the gruvbox material theme :)

Gruvbox Material Light Theme

---

themes/Ayaka.yml

added Ayaka theme :3

---

themes/Monokai Pro.yml

fix monokai pro bg & fg according to https://monokai.pro

---

themes/Minimalist Dark.yml

Changed magenta and green default color for contrast

refactor: magenta and green - Minimalist Dark default color

---

themes/acme.yml

hi there, i just added acme theme to this repo. 
source: https://github.com/plan9-for-vimspace/acme-colors

add acme theme

---

themes/Acme.yml
themes/Blue Moon Light.yml
themes/Blue Moon.yml

i just fixed the acme file name (sorry for that) and added new themes from:
https://github.com/kyazdani42/blue-moon
thank you

add blue moon themes and fixing file name

---

README.md
apply-colors.sh

Implement Wezterm support in apply-colors.sh using Dynamic Color Escape Sequences.

Add Wezterm terminal support

---

themes/Acme.yml
themes/Blue Moon Light.yml
themes/Blue Moon.yml
tools/pipe-generateJson.py
tools/pipe-generateShFiles.py

YAML does not allow tabs. (Bad things eventually happen if you allow tabs in your yaml files).
https://yaml.org/faq.html
Fixes offending theme files & build scripts.

YAML does not allow tabs.
