Gogh-Co/Gogh

_apply-colors.sh
I'm at elementaryOS but I don't use pantheon-terminal. The current script try to change based on my OS, instead on which terminal I'm actually using.
Changed this and now the script try to infer the terminal being used.
=> [Hotfix] Using terminal name instead OS

themes/solarized.dark.sh
The previous state of Solarized Dark color scheme was making part of the info shown on htop go missing because a text color was set to the same color as terminal background as you can check down below:
Old state of the color scheme:
New state of the color scheme:
=> Problem with text exhibition on htop when using Solarized Dark theme

apply-colors.sh
This pull request adds mate-terminal support as requested in issue #37. 
The user must have dconf-cli installed.
=> add support for mate-terminal

gogh.sh
* Multiple themes can be installed in one instance - theme selection numbers should be seperated by space as before
* Respective theme name is now properly shown instead of the last assignment of `FILENAME_SPACE` viz. the Last theme's name
_Tested on KDE Neon with GNOME Terminal, works._
=> Gogh: Improvements

content/themes.md, gh-pages/index.html, test/test.sh
The previously shorten URL that was used to install the Solarized Dark theme was not working because was pointing to a non existent file. The new shorten URL is pointing to the existent theme file into the repository.
=> Fixing the problem with the installation of the Solarized Dark theme

gogh.sh
Resolves issue #102 by calling the respective theme via `source`.
=> Fixed $TERMINAL containing name of shell

apply-colors.sh
Resolves issue #27 by writing a temporary iTerm2 color scheme file (`*.itermcolors`), importing it and deleting it afterwards. This approach does not require restarting iTerm2.
Tested in two OSXs and made sure the changes do not affect existing functionality for Linux. You can try running some theme script in iTerm2 on your own - it should work.
Unfortunately, the `gogh_colors` function which is present in every theme script, does not work properly in OSX (see below):
Calling the function directly from terminal works though (see working scheme below):
While this is just a cosmetic issue and can certainly be fixed in some way, I won't do so until I get some feedback on my approach. I just don't want to invest more time into it if you have a better approach for supporting iTerm2 in mind. If …
=> Added iTerm2 support

themes/one-half-black.sh, themes/one-half-dark.sh
As the title states, this one adds a variant of "One Half Dark" theme from [here](https://github.com/sonph/onehalf).
An adaptation was needed as the original theme uses the same colour for both `COLOR_01` and `BACKGROUND_COLOR`, making many applications (e.g. `htop`) illegible. Here the background was set to pure black (thus the naming of the variant: "One Half Black").
Let me know if something still needs to be done for this pull request to be accepted.
=> Added a variant of "One Half Dark"

README.md, apply-colors.sh, gogh.sh, themes/_base.sh
- Format README.md and add links to theme authors
- Fix indentation in gogh.sh
- Modify comments to identify colors by their name rather than their
use
- shellcheck errors
- quote variables in most places to prevent word globbing
- use $(cmd) instead of legacy \`cmd\`
=> Minor tweaks

index.html
It tried to point to https://raw.githubusercontent.com/Mayccoll/Gogh/master/themes/tomorrow.night.sh instead of https://raw.githubusercontent.com/Mayccoll/Gogh/master/themes/tomorrow-night.sh (the filename had a dot instead of a hyphen)
=> Link to Tomororw Night Theme 404'd

themes/gruvbox.sh
The `themes/gruvbox.sh` file was just a one-to-one match on the `gruvbox-dark.sh` file. I think `gruvbox.sh` was intentionally supposed to be the light version
See original README for correct color codes:
https://github.com/morhetz/gruvbox
=> Fix gruvbox.sh with light colors instead of dark colors

apply-colors.sh
This change allow the environment to specify the value for `TERMINAL`. This is useful if you aren't running the theme script directly. For example, using a script like this:
```sh
#/usr/bin/env bash
set -e
(
cd /tmp
wget --quiet -O xt "https://raw.githubusercontent.com/Mayccoll/Gogh/master/themes/$1.sh"
chmod +x xt
TERMINAL=pantheon-terminal ./xt
rm xt
)
```
=> Allow TERMINAL to be set by environment

gh-pages/index.html
I noticed that on the webpage http://mayccoll.github.io/Gogh/ the command for installing themes only installs Freya theme. Here is a PR to replace it with the command from GitHub README, which allows to chose from the full list of themes.
=> Update command to install themes in gh-pages

README.md
The installer script create profile with id as the theme name. uuid-runtime package is needed to generate random id for profile, so terminal can read the new profile.
=> Add uuid-runtime on pre-install

gh-pages/index.src.html
The command with '$' prompt at the start throws an error while copying and pasting the command into the terminal.
=> Fix command statement

themes/night-owl.sh
This theme is based on the [Night Owl theme available for vscode](https://github.com/sdras/night-owl-vscode-theme). 
Example of the colour scheme can be found below:
=> Add Night Owl theme

themes/flat-remix.sh
Color-scheme based on [Flat-Remix](https://github.com/daniruiz/flat-remix) icon theme palette
=> Add Flat Remix theme

themes/ir-black.sh, themes/synthwave.sh
There were two themes whose cursor color had a missing "#" prefix:
- ir-black
- synthwave
I discovered these issues while generating a json list with all themes for use in the Windows Terminal Config ([result](https://gist.github.com/rapgru/09b449285231d18f4e4536c5f48fc927)). This is unrelated to the problem fixed in this PR, but maybe you could somehow use this gist or place a link in the README.
=> Insert missing # in cursor colors

themes/horizon-bright.sh, themes/horizon-dark.sh
Fix light gray (COLOR_08) being too dark in both Horizon themes.
Signed-off-by: Przemysław Lal <przemeklal@gmail.com>
=> Fix light gray in Horizon themes

themes/nord.sh
Change the `Nord` colours to match https://github.com/arcticicestudio/nord-gnome-terminal
=> Change the Nord colours to match the official port

themes/google-dark.sh, themes/google-light.sh
This updates the Google theme to their official colors: https://github.com/google/vim-colorscheme-primary
I know that the existing theme is based off of the base16 repository (https://github.com/chriskempson/base16).  I would say that it would be worth adding this Google dark and light theme as separate theme if Gogh included the whole base16 ecosystem.  But since it is the only base16 labeled theme, I propose replacing it.  If you disagree, I can resubmit as a separate theme.
=> Update Google Light and Dark theme

apply-colors.sh
I found that Gnome sets $HIGHLIGHT_BG_COLOR to "#" when run through the gnome color fcn.  I added a check for empty colors to gnome_color.  I also found that the cursor was getting set to a non-specified color on gnome so I added setting the cursor to the specified color in set_theme.
Resolves #268
=> Fix bug where gnome sets Highlight color even when nonexistant

content/howto.md
This pull request fixes a link to the _base script in the howto docs. Initially it was pointing to /themes/_base.sh, but at some point this script was moved to /_base.sh
=> Fix link to base script in howto docs

.gitattributes
This PR adds a .gitattributes file that marks *data/themes.json* as binary. *data/themes.json* stores all it's data on a single line, and that entire line is marked as changed between commits. By marking it as binary, git displays diffs more accurately.
For example, instead of printing out the entirety of *data/themes.json*, git will instead say "Binary files *version 1* *version 2* differ"
**NB:** As an alternative to marking it as binary, we could also modify *tools/generate.sh* so that it doesn't generate the entire file on one line. This can be done by removing the `tr -d " \t\n\r"` portion of the script. Doing so would ensure that git only stored the sections of the themes.json file that changed when a theme was modified or added.
=> Mark data/themes.json as a binary file

themes/nord-light.sh
Update Nord Light theme to improve usability and make the black and grey colors a dark blue.
Prior to this change, it was extremely difficult to read green text with Nord Light because the green was such a light color that the text was hard to discern against the background.
Green text is common in the output of commands like `git diff`, and many zsh themes use green text to indicate the existence of a command. This commit  updates Nord Light to use a darker green that's still in line with the theme.
This PR also updates Black to be dark blue, and Grey to be blue-grey. Using dark blue and blue-grey colors for Black and Grey respectively is more in line with the style choices made by the Nord theme. I've provided relevant before and after shots below, with the previous version being on the …
=> Increase Usability and Consistency of Nord Light

themes/monokai-pro-ristretto.sh
I initially took the values from the Monokai Pro VS Code extension, but that did not result in the same appearance. Instead I used a color picker to get the visually correct colors. 
I assume it's caused by Gnome Terminal and VS Code using different color spaces.
=> Add Monokai Pro Ristretto

apply-colors.sh
I am a long-time user of Gogh, but I have recently hopped distros and am now using KDE + Konsole. As such, I decided to add Konsole support (and by extension yaquake support).
I have mostly copied the code style from the kitty and mintty functions: `apply_konsole` is based on `apply_kitty`, and `createKonsoleEntry` and `createKonsoleTriple` are based on `createMinttyEntry`.
Several issues I encountered while developing this:
1. Konsole has very extensive profiles, meaning that the profiles also store information about font, keybinds, tabs, etc. In my implementation, every profile that is generated by Gogh sets the current default profile as its 'parent', meaning that the Gogh profiles don't have to specify fonts.
2. `${TERMINAL}` gets set to `konsole` using the automatic `ps` script.
3. …
=> Added support for Konsole

themes/sonokai.sh
I used the same color for normal gray and bold gray. However, gnome terminal uses "bold gray" for displaying autocompletion stuff in node for instance. So it needs to differ.
=> fix gray for sonokai

themes/catppuccin-mocha.sh
themes.json isn't fully parseable in wezterm's import machinery because of these broken color definitions:
```json
{
"name": "CatppuccinMocha",
"black": "#45475A",
"red": "#F38BA8",
"green": "#A6E3A1",
"yellow": "#F9E2AF",
"blue": "#89B4FA",
"purple": "#F5C2E7",
"cyan": "#94E2D5",
"white": "#BAC2DE",
"brightBlack": "#585B70",
"brightRed": "#F38BA8",
"brightGreen": "#A6E3A1",
"brightYellow": "#F9E2AF",
"brightBlue": "#89B4FA",
"brightPurple": "#F5C2E7",
"brightCyan": "#94E2D5",
"brightWhite": "#A6ADC8",
"foreground": "#",
"background": "#",
"cursorColor": "#"
},
```
Colors are inserted here based on the upstream:
https://github.com/catppuccin/wezterm/blob/main/dist/catppuccin-mocha.toml#L12 https://github.com/catppuccin/wezterm/blob/main/dist/catppuccin-mocha.toml#L27
=> Fix broken colors in Catppuccin Mocha

gogh.sh, installs/gruvbox-material.sh, themes/Gruvbox Material.yml
Added Gruvbox Material (dark medium) theme. Adapted from the original author theme for Alacrity [here](https://gist.github.com/sainnhe/ad5cbc4f05c4ced83f80e54d9a75d22f)
=> Add Gruvbox Material (dark medium) theme

themes/Everforest Dark.yml
Sync with upstream changes: https://github.com/sainnhe/everforest/compare/d855af5434...81041b4033
No changes to foreground colors seem required.
---
Preview:
[before]: https://fakeimg.pl/96/2F383E/D3C6AA/?text=before "before"
[now]: https://fakeimg.pl/96/2D353B/D3C6AA/?text=now "now"
=> Update background color of Everforest Dark theme

apply-alacritty.py
According to https://github.com/alacritty/alacritty/tree/master#configuration, the configure file should be in following path
1. $XDG_CONFIG_HOME/alacritty/alacritty.yml
2. $XDG_CONFIG_HOME/alacritty.yml
3. $HOME/.config/alacritty/alacritty.yml
4. $HOME/.alacritty.yml
but paths in script do not fully match these paths, this patch fix this problem.
=> Fix alacritty config path mismatch with it's doc

themes/Terminal Basic.yml
Sample on Gnome-Terminal:
Reference:
[iTerm2 Remmina Terminal-Basic](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/remmina/Terminal%20Basic.colors)
=> Add Terminal-Basic colorscheme, based on iTerm2

apply-colors.sh, gogh.sh
Added support for Linux virtual terminals.
Themes are put in ~/.vtrgb-gogh when installed as a user. The colors can be set by calling setvtrgb. For example
> setvtrgb ~/.vtrgb-gogh/Tin
This can be done in your .bashrc file to set your color scheme.
When running the gogh.sh script as root, theme files are put into /usr/local/share/vtrgb-gogh and under Debian based systems the installed themes are installed as alternatives to the default colors in /etc/vtrgb and can be set as the default system theme using
> sudo update-alternatives --config vtrgb
=> Added support for Linux virtual terminal.

apply-colors.sh
From the man page:
> You can reload the config file within kitty by pressing ctrl+shift+f5 (⌃+⌘+, on macOS) or sending kitty the SIGUSR1 signal.
This patch sends kitty a signal to hot-reload the config after it's done. Because I recall some weird systems not including one of either `killall` or `pkill` in the past let's just try them both. (The `||` operator is short for "if the command to the left fails (exit code >= 1), run the command on the right." So first we try `killall`, and then we try `pkill`. We also ask both commands to filter by the current user, so as to not attempt to ask another user's kitty process to reload (and so as not to cause an error because we tried).
It should be noted that doing this on macOS an old version of Kitty from before August 2021 will actually kill …
=> Feat: apply_kitty(): reload config after applying theme

themes/Github Dark.yml, themes/Github Light.yml
The current `Github` theme is the Github Light theme.
So added the `Github Dark` theme and updated the previous `Github` theme name to `Github Light`.
I've assumed that the bot will rename the old github theme to github light everywhere. Should I manually do this?
=> Added the Github Dark Theme.

themes/Github Light.yml
Github Light contrast is hardly readable. I matched it with @primer/github-vscode-theme [Github Light Default](https://github.com/primer/github-vscode-theme/blob/38b50d41bdc6b190b7351e220956af043221d763/src/theme.js#L282), but made green and yellow slighly brighter.
Before
After
=> fix github-light theme contrast

themes/Kanagawa Dragon.yaml
This PR adds the _Dragon_ Variant of the [Kanagawa Theme](https://github.com/rebelot/kanagawa.nvim).
Based on this reference: https://github.com/rebelot/kanagawa.nvim/blob/master/extras/Kanagawa%20Dragon.json
=> Kanagawa Dragon Variant

themes/Solarized Dark.yml
Solarized has not bright colors versions, but it has orange and violet colors. I made fixes regardin this
See :  https://ethanschoonover.com/solarized/
=> Update Solarized Dark.yml

themes/Selenized Black.yml, themes/Selenized Dark.yml, themes/Selenized Light.yml, themes/Selenized White.yml
Add and fix four Selenized themes according official values for sRGB:
- [Color mapping](https://github.com/jan-warchol/selenized/blob/master/manual-installation.md)
- [Color coordinates](https://github.com/jan-warchol/selenized/blob/master/the-values.md)
```
Selenized mapping
==================
color_01: # Black (Host) - [bg_1]
color_02: # Red (Syntax string) - [red]
color_03: # Green (Command) - [green]
color_04: # Yellow (Command second) - [yellow]
color_05: # Blue (Path) - [blue]
color_06: # Magenta (Syntax var) - [magenta]
color_07: # Cyan (Prompt) - [cyan]
color_08: # White - [dim_0]
color_09: # Bright Black - [bg_2]
color_10: # Bright Red (Command error) - [br_red]
color_11: # Bright Green (Exec) - [br_green]
color_12: # Bright Yellow - [br_yellow]
color_13: # Bright Blue (Folder) - …
```
=> add and fix selenized themes

themes/Breadog.yml
[Breadog] is a light theme I made with the goal of keeping contrast high, lightness among colors consistent, and the overall appearance pleasant to look at.
[Breadog]: https://gitlab.com/warningnonpotablewater/breadog
Here are some screenshots:
=> Add the Breadog theme

README.md
Add `pacman` commands for pre-install instructions.
=> Add pre-install instructions for Arch Linux

apply-colors.sh
On the latest version of Arch Linux it appears that guake does not respect the options set by `dconf` but does respect `gsettings`. Added support for attempting to use `gsettings` first before trying `dconf`, and finally `gconf`.
=> Prefer using gsettings for guake if available

apply-colors.sh
Add missing space so that the script does not throw syntax error
=> fix: Add missing space to condition

gogh.sh
I wish we could just pipe the theme list to `/usr/bin/column`, but:
- column has a hard-coded tab size of 8
- fails catastrophically when the terminal tab size is not 8
- uses hard-coded tabs for formatting (no option to use spaces)
- does not support ANSI escape codes (a fix was merged in Feb, but not released yet)
Since the algorithm is trivial, we might as well implement it in bash.
Note: the columns are as large as the largest entry. Currently, the biggest entry is solarized-dark-higher-contrast with a length of 30, so columns are 40 characters wide, inc. ( NUM ).
Note: this branch (and PR) contains my other commit from PR #453. If both are to be accepted, merging this one alone should be enough.
=> Use a column display for themes.

gogh.sh
We can now use `$C4` instead of `$(tput setaf 4)`, `$C12` for color 12, etc.
I'm not sure if there's a difference between `tput sgr0` and `tput sgr 0` so each got their own variable (resp. CR and CS0).
=> Caching calls to tput into variables

apply-colors.sh
This commit will make Gogh automatically create a foot configuration file,
so the theme values can be saved into it.
But only if it didn't exist beforehand.
This eases the user configuration as foot doesn't come with a configuration shipped by default and the user doesn't need to manually copy the config file from foot's source
=> Automatically create foot config if it does not exist

apply-colors.sh
when Gogh creates profiles for Gnome Terminal, it does not set `highlight-colors-set` explicitly. this causes hightlight settings to be inherited from currently selected default profile, cuz Gogh's themes does not (yet) define highlight (even if there is code to support it).
example, "native" (not Gogh's versions) Catppuccin and Nord themes do define highlight settings, Catppuccin is my current default
now, if i use Gogh to install eg Tomorrow Night Eighties, then highlight is copied from Catppuccin
but the proper look (without highlight color support in themes) is this
all in all, it's just 1 line fix :)
=> fixed wrong highlight color inheritance in Gnome Terminal

themes/Kanagawa.yml
Here is current White(1) and Bright White(2) colors. As you can see "white" is brighter than "bright white".
=> Swapped Kanagawa's White and Bright White colors since they are mismatched

README.md, themes/Vaombe.yml
This pull request is designed to implement my custom color palette that I call "Vaombe". With some hard work tweaking it to perfection as well as sacrificing non-valuable storage space, this color palette functions well across many terminal-based applications. Vaombe was designed as part of my project called "Aloemint" which is an Operating System that I design in my free time.
* ``themes/Vaombe.yml``
* ``README.md`` (Updated with grammatical corrections, as well as hinting Vaombe.)
Oh, and if you need anything else; I would be glad to cooperate!
Thanks,
Daniel Perez.
=> Implement Vaombe Theme
